name: Publish to CodeArtifact

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
jobs:
  publish:
    if: "!contains(github.event.head_commit.message, '[skip publish]')"
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to CodeArtifact
        run: |
          aws codeartifact login --tool npm --repository ${{ secrets.CODEARTIFACT_REPOSITORY }} --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --region ${{ secrets.AWS_REGION }}

      - name: Publish to CodeArtifact
        run: npm publish
